/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmergencyContact {
  'id' : EmergencyContactID,
  'owner' : Principal,
  'name' : string,
  'phoneNumber' : string,
}
export type EmergencyContactID = bigint;
export type EvidenceID = bigint;
export interface EvidenceRecord {
  'id' : EvidenceID,
  'owner' : Principal,
  'description' : string,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'incidentType' : string,
}
export interface LegalArticle {
  'id' : LegalArticleID,
  'title' : string,
  'content' : string,
  'category' : string,
}
export type LegalArticleID = bigint;
export interface Updates {
  'displayName' : string,
  'pinEnabled' : boolean,
  'pinHash' : string,
}
export interface UserProfile {
  'sosTimestamp' : [] | [bigint],
  'displayName' : string,
  'user' : Principal,
  'isSosActive' : boolean,
  'pinEnabled' : boolean,
  'pinHash' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContact' : ActorMethod<[string, string], EmergencyContactID>,
  'addEvidenceRecord' : ActorMethod<
    [string, string, [] | [string]],
    EvidenceID
  >,
  'addLegalArticle' : ActorMethod<[string, string, string], LegalArticleID>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSOS' : ActorMethod<[], undefined>,
  'deleteEvidenceRecord' : ActorMethod<[EvidenceID], undefined>,
  'getAllLegalArticles' : ActorMethod<[], Array<LegalArticle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentSOSState' : ActorMethod<[], boolean>,
  'getDisplayName' : ActorMethod<[], string>,
  'getLegalArticle' : ActorMethod<[LegalArticleID], LegalArticle>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUserContacts' : ActorMethod<[], Array<EmergencyContact>>,
  'listUserEvidenceRecords' : ActorMethod<[], Array<EvidenceRecord>>,
  'removeContact' : ActorMethod<[EmergencyContactID], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDefaultLegalArticles' : ActorMethod<[], undefined>,
  'triggerSOS' : ActorMethod<[], undefined>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'upsertSettings' : ActorMethod<[Updates], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];