/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmergencyContactID = IDL.Nat;
export const EvidenceID = IDL.Nat;
export const LegalArticleID = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LegalArticle = IDL.Record({
  'id' : LegalArticleID,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'sosTimestamp' : IDL.Opt(IDL.Int),
  'displayName' : IDL.Text,
  'user' : IDL.Principal,
  'isSosActive' : IDL.Bool,
  'pinEnabled' : IDL.Bool,
  'pinHash' : IDL.Opt(IDL.Text),
});
export const EmergencyContact = IDL.Record({
  'id' : EmergencyContactID,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const EvidenceRecord = IDL.Record({
  'id' : EvidenceID,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'incidentType' : IDL.Text,
});
export const Updates = IDL.Record({
  'displayName' : IDL.Text,
  'pinEnabled' : IDL.Bool,
  'pinHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Text, IDL.Text], [EmergencyContactID], []),
  'addEvidenceRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [EvidenceID],
      [],
    ),
  'addLegalArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [LegalArticleID],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSOS' : IDL.Func([], [], []),
  'deleteEvidenceRecord' : IDL.Func([EvidenceID], [], []),
  'getAllLegalArticles' : IDL.Func([], [IDL.Vec(LegalArticle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentSOSState' : IDL.Func([], [IDL.Bool], ['query']),
  'getDisplayName' : IDL.Func([], [IDL.Text], ['query']),
  'getLegalArticle' : IDL.Func([LegalArticleID], [LegalArticle], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUserContacts' : IDL.Func([], [IDL.Vec(EmergencyContact)], ['query']),
  'listUserEvidenceRecords' : IDL.Func(
      [],
      [IDL.Vec(EvidenceRecord)],
      ['query'],
    ),
  'removeContact' : IDL.Func([EmergencyContactID], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDefaultLegalArticles' : IDL.Func([], [], []),
  'triggerSOS' : IDL.Func([], [], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'upsertSettings' : IDL.Func([Updates], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmergencyContactID = IDL.Nat;
  const EvidenceID = IDL.Nat;
  const LegalArticleID = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LegalArticle = IDL.Record({
    'id' : LegalArticleID,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'sosTimestamp' : IDL.Opt(IDL.Int),
    'displayName' : IDL.Text,
    'user' : IDL.Principal,
    'isSosActive' : IDL.Bool,
    'pinEnabled' : IDL.Bool,
    'pinHash' : IDL.Opt(IDL.Text),
  });
  const EmergencyContact = IDL.Record({
    'id' : EmergencyContactID,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const EvidenceRecord = IDL.Record({
    'id' : EvidenceID,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'incidentType' : IDL.Text,
  });
  const Updates = IDL.Record({
    'displayName' : IDL.Text,
    'pinEnabled' : IDL.Bool,
    'pinHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Text, IDL.Text], [EmergencyContactID], []),
    'addEvidenceRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [EvidenceID],
        [],
      ),
    'addLegalArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [LegalArticleID],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSOS' : IDL.Func([], [], []),
    'deleteEvidenceRecord' : IDL.Func([EvidenceID], [], []),
    'getAllLegalArticles' : IDL.Func([], [IDL.Vec(LegalArticle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentSOSState' : IDL.Func([], [IDL.Bool], ['query']),
    'getDisplayName' : IDL.Func([], [IDL.Text], ['query']),
    'getLegalArticle' : IDL.Func([LegalArticleID], [LegalArticle], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUserContacts' : IDL.Func([], [IDL.Vec(EmergencyContact)], ['query']),
    'listUserEvidenceRecords' : IDL.Func(
        [],
        [IDL.Vec(EvidenceRecord)],
        ['query'],
      ),
    'removeContact' : IDL.Func([EmergencyContactID], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDefaultLegalArticles' : IDL.Func([], [], []),
    'triggerSOS' : IDL.Func([], [], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'upsertSettings' : IDL.Func([Updates], [], []),
  });
};

export const init = ({ IDL }) => { return []; };